"""soft_delete_aware_unique_indexes

Revision ID: 7e1e98e95ace
Revises: ed72b3fc94e8
Create Date: 2026-07-13 22:11:12.935655
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1e98e95ace'
down_revision: str | None = 'ed72b3fc94e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cart_item_extras_item_option'), 'cart_item_extras', type_='unique')
    op.create_index('uq_cart_item_extras_item_option_active', 'cart_item_extras', ['cart_item_id', 'option_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_coupon_usages_coupon_order'), 'coupon_usages', type_='unique')
    op.create_index('uq_coupon_usages_coupon_order_active', 'coupon_usages', ['coupon_id', 'order_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_deal_products_deal_product'), 'deal_products', type_='unique')
    op.create_index('uq_deal_products_deal_product_active', 'deal_products', ['deal_id', 'product_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_product_options_product_option'), 'product_options', type_='unique')
    op.create_index('uq_product_options_product_option_active', 'product_options', ['product_id', 'option_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_product_variants_product_size'), 'product_variants', type_='unique')
    op.create_index('uq_product_variants_product_size_active', 'product_variants', ['product_id', 'size'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_wishlist_items_wishlist_product'), 'wishlist_items', type_='unique')
    op.create_index('uq_wishlist_items_wishlist_product_active', 'wishlist_items', ['wishlist_id', 'product_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_wishlist_items_wishlist_product_active', table_name='wishlist_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_wishlist_items_wishlist_product'), 'wishlist_items', ['wishlist_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_product_variants_product_size_active', table_name='product_variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_product_variants_product_size'), 'product_variants', ['product_id', 'size'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_product_options_product_option_active', table_name='product_options', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_product_options_product_option'), 'product_options', ['product_id', 'option_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_deal_products_deal_product_active', table_name='deal_products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_deal_products_deal_product'), 'deal_products', ['deal_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_coupon_usages_coupon_order_active', table_name='coupon_usages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_coupon_usages_coupon_order'), 'coupon_usages', ['coupon_id', 'order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_cart_item_extras_item_option_active', table_name='cart_item_extras', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_cart_item_extras_item_option'), 'cart_item_extras', ['cart_item_id', 'option_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
