"""email_logs_transactional_notifications

Revision ID: d789ba8517ef
Revises: 48fcbb9cf907
Create Date: 2026-07-14 00:15:34.193277
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd789ba8517ef'
down_revision: str | None = '48fcbb9cf907'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('template_key', sa.Enum('owner_new_order', 'owner_test', 'order_confirmation', 'order_cancelled', 'order_delivered', 'passwordless_login', name='email_template_key'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'failed', 'skipped', name='email_delivery_status'), server_default='queued', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_deleted_at'), 'email_logs', ['deleted_at'], unique=False)
    op.create_index('ix_email_logs_order_id', 'email_logs', ['order_id'], unique=False)
    op.create_index('ix_email_logs_recipient', 'email_logs', ['recipient'], unique=False)
    op.create_index('ix_email_logs_status', 'email_logs', ['status'], unique=False)
    op.create_index('ix_email_logs_template_key', 'email_logs', ['template_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_email_logs_template_key", table_name="email_logs")
    op.drop_index("ix_email_logs_status", table_name="email_logs")
    op.drop_index("ix_email_logs_recipient", table_name="email_logs")
    op.drop_index("ix_email_logs_order_id", table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_deleted_at"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_created_at"), table_name="email_logs")
    op.drop_table("email_logs")
    op.execute("DROP TYPE IF EXISTS email_template_key")
    op.execute("DROP TYPE IF EXISTS email_delivery_status")
