"""create_prime_pizza_schema

Revision ID: ed72b3fc94e8
Revises: 
Create Date: 2026-07-13 22:02:00.891720
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed72b3fc94e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_index('ix_categories_display_order', 'categories', ['display_order'], unique=False)
    op.create_index('ix_categories_is_visible', 'categories', ['is_visible'], unique=False)
    op.create_index('uq_categories_slug_active', 'categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coupon_type', sa.Enum('percentage', 'fixed', name='coupon_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maximum_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("coupon_type <> 'percentage' OR value <= 100", name='ck_coupons_percentage_max_100'),
    sa.CheckConstraint('maximum_discount IS NULL OR maximum_discount >= 0', name='ck_coupons_max_discount_non_negative'),
    sa.CheckConstraint('minimum_order_amount IS NULL OR minimum_order_amount >= 0', name='ck_coupons_min_order_non_negative'),
    sa.CheckConstraint('per_user_limit IS NULL OR per_user_limit >= 0', name='ck_coupons_per_user_limit_non_negative'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit >= 0', name='ck_coupons_usage_limit_non_negative'),
    sa.CheckConstraint('value >= 0', name='ck_coupons_value_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_created_at'), 'coupons', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupons_deleted_at'), 'coupons', ['deleted_at'], unique=False)
    op.create_index('ix_coupons_expires_at', 'coupons', ['expires_at'], unique=False)
    op.create_index('ix_coupons_is_active', 'coupons', ['is_active'], unique=False)
    op.create_index('uq_coupons_code_active', 'coupons', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('deals',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deal_type', sa.Enum('combo', 'family', 'limited', 'time_based', name='deal_type'), nullable=False),
    sa.Column('deal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('deal_price >= 0', name='ck_deals_price_non_negative'),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at', name='ck_deals_ends_after_starts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index('ix_deals_deal_type', 'deals', ['deal_type'], unique=False)
    op.create_index(op.f('ix_deals_deleted_at'), 'deals', ['deleted_at'], unique=False)
    op.create_index('ix_deals_ends_at', 'deals', ['ends_at'], unique=False)
    op.create_index('ix_deals_is_active', 'deals', ['is_active'], unique=False)
    op.create_index('ix_deals_starts_at', 'deals', ['starts_at'], unique=False)
    op.create_index('uq_deals_slug_active', 'deals', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('otp_logs',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'expired', 'failed', name='otp_verification_status'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('provider_sid', sa.String(length=100), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_logs_created_at', 'otp_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_logs_deleted_at'), 'otp_logs', ['deleted_at'], unique=False)
    op.create_index('ix_otp_logs_expires_at', 'otp_logs', ['expires_at'], unique=False)
    op.create_index('ix_otp_logs_phone_number', 'otp_logs', ['phone_number'], unique=False)
    op.create_index('ix_otp_logs_status', 'otp_logs', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_deleted_at'), 'system_settings', ['deleted_at'], unique=False)
    op.create_index('ix_system_settings_is_public', 'system_settings', ['is_public'], unique=False)
    op.create_index('uq_system_settings_key_active', 'system_settings', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('customer', 'owner', name='user_role'), server_default='customer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.create_index('uq_users_phone_active', 'users', ['phone_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('variant_options',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('option_type', sa.Enum('topping', 'sauce', 'crust', 'extra', 'other', name='variant_option_type'), server_default='topping', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_variant_options_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_options_created_at'), 'variant_options', ['created_at'], unique=False)
    op.create_index(op.f('ix_variant_options_deleted_at'), 'variant_options', ['deleted_at'], unique=False)
    op.create_index('ix_variant_options_option_type', 'variant_options', ['option_type'], unique=False)
    op.create_index('uq_variant_options_slug_active', 'variant_options', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('addresses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='Pakistan', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_created_at'), 'addresses', ['created_at'], unique=False)
    op.create_index(op.f('ix_addresses_deleted_at'), 'addresses', ['deleted_at'], unique=False)
    op.create_index('ix_addresses_user_id', 'addresses', ['user_id'], unique=False)
    op.create_index('uq_addresses_default_per_user', 'addresses', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND is_default IS TRUE'))
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'view', 'other', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_created_at'), 'carts', ['created_at'], unique=False)
    op.create_index(op.f('ix_carts_deleted_at'), 'carts', ['deleted_at'], unique=False)
    op.create_index('ix_carts_user_id', 'carts', ['user_id'], unique=False)
    op.create_index('uq_carts_user_active', 'carts', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND is_active IS TRUE'))
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('marketing_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_created_at'), 'notification_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_preferences_deleted_at'), 'notification_preferences', ['deleted_at'], unique=False)
    op.create_index('uq_notification_preferences_user_active', 'notification_preferences', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notification_type', sa.Enum('order', 'promo', 'system', 'account', name='notification_type'), server_default='system', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_products_base_price_non_negative'),
    sa.CheckConstraint('calories IS NULL OR calories >= 0', name='ck_products_calories_non_negative'),
    sa.CheckConstraint('discount_price IS NULL OR discount_price <= base_price', name='ck_products_discount_lte_base'),
    sa.CheckConstraint('discount_price IS NULL OR discount_price >= 0', name='ck_products_discount_price_non_negative'),
    sa.CheckConstraint('preparation_time_minutes IS NULL OR preparation_time_minutes >= 0', name='ck_products_prep_time_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index('ix_products_is_available', 'products', ['is_available'], unique=False)
    op.create_index('ix_products_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('ix_products_is_popular', 'products', ['is_popular'], unique=False)
    op.create_index('ix_products_is_visible', 'products', ['is_visible'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('uq_products_slug_active', 'products', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('wishlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_created_at'), 'wishlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_wishlists_deleted_at'), 'wishlists', ['deleted_at'], unique=False)
    op.create_index('ix_wishlists_user_id', 'wishlists', ['user_id'], unique=False)
    op.create_index('uq_wishlists_user_active', 'wishlists', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('deal_products',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_deal_products_quantity_positive'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'product_id', name='uq_deal_products_deal_product')
    )
    op.create_index(op.f('ix_deal_products_created_at'), 'deal_products', ['created_at'], unique=False)
    op.create_index('ix_deal_products_deal_id', 'deal_products', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_products_deleted_at'), 'deal_products', ['deleted_at'], unique=False)
    op.create_index('ix_deal_products_product_id', 'deal_products', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('delivery_address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled', 'refunded', name='order_status'), server_default='pending', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash_on_delivery', 'card', 'online', 'wallet', name='payment_method'), server_default='cash_on_delivery', nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'partially_refunded', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('delivery_fee >= 0', name='ck_orders_delivery_fee_non_negative'),
    sa.CheckConstraint('discount >= 0', name='ck_orders_discount_non_negative'),
    sa.CheckConstraint('grand_total >= 0', name='ck_orders_grand_total_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_orders_subtotal_non_negative'),
    sa.CheckConstraint('tax >= 0', name='ck_orders_tax_non_negative'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_deleted_at'), 'orders', ['deleted_at'], unique=False)
    op.create_index('ix_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('uq_orders_order_number_active', 'orders', ['order_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_created_at'), 'product_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_images_deleted_at'), 'product_images', ['deleted_at'], unique=False)
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_index('uq_product_images_primary', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND is_primary IS TRUE'))
    op.create_index('uq_product_images_product_order_active', 'product_images', ['product_id', 'display_order'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('product_options',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['variant_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'option_id', name='uq_product_options_product_option')
    )
    op.create_index(op.f('ix_product_options_created_at'), 'product_options', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_options_deleted_at'), 'product_options', ['deleted_at'], unique=False)
    op.create_index('ix_product_options_option_id', 'product_options', ['option_id'], unique=False)
    op.create_index('ix_product_options_product_id', 'product_options', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', 'family', 'custom', name='variant_size'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_product_variants_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size', name='uq_product_variants_product_size')
    )
    op.create_index(op.f('ix_product_variants_created_at'), 'product_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_variants_deleted_at'), 'product_variants', ['deleted_at'], unique=False)
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'product_id', name='uq_wishlist_items_wishlist_product')
    )
    op.create_index(op.f('ix_wishlist_items_created_at'), 'wishlist_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_wishlist_items_deleted_at'), 'wishlist_items', ['deleted_at'], unique=False)
    op.create_index('ix_wishlist_items_product_id', 'wishlist_items', ['product_id'], unique=False)
    op.create_index('ix_wishlist_items_wishlist_id', 'wishlist_items', ['wishlist_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extras_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_items_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_cart_items_subtotal_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_cart_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_created_at'), 'cart_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_cart_items_deleted_at'), 'cart_items', ['deleted_at'], unique=False)
    op.create_index('ix_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    op.create_index('ix_cart_items_variant_id', 'cart_items', ['variant_id'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'order_id', name='uq_coupon_usages_coupon_order')
    )
    op.create_index('ix_coupon_usages_coupon_id', 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index('ix_coupon_usages_created_at', 'coupon_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupon_usages_deleted_at'), 'coupon_usages', ['deleted_at'], unique=False)
    op.create_index('ix_coupon_usages_order_id', 'coupon_usages', ['order_id'], unique=False)
    op.create_index('ix_coupon_usages_user_id', 'coupon_usages', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_slug', sa.String(length=220), nullable=True),
    sa.Column('variant_name', sa.String(length=100), nullable=True),
    sa.Column('variant_size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extras_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_items_subtotal_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_deleted_at'), 'order_items', ['deleted_at'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_table('cart_item_extras',
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_item_extras_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_cart_item_extras_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['variant_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_item_id', 'option_id', name='uq_cart_item_extras_item_option')
    )
    op.create_index('ix_cart_item_extras_cart_item_id', 'cart_item_extras', ['cart_item_id'], unique=False)
    op.create_index(op.f('ix_cart_item_extras_created_at'), 'cart_item_extras', ['created_at'], unique=False)
    op.create_index(op.f('ix_cart_item_extras_deleted_at'), 'cart_item_extras', ['deleted_at'], unique=False)
    op.create_index('ix_cart_item_extras_option_id', 'cart_item_extras', ['option_id'], unique=False)
    op.create_table('order_item_extras',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('option_name', sa.String(length=150), nullable=False),
    sa.Column('option_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_order_item_extras_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_item_extras_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['option_id'], ['variant_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_extras_created_at'), 'order_item_extras', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_item_extras_deleted_at'), 'order_item_extras', ['deleted_at'], unique=False)
    op.create_index('ix_order_item_extras_order_item_id', 'order_item_extras', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_item_extras_order_item_id', table_name='order_item_extras')
    op.drop_index(op.f('ix_order_item_extras_deleted_at'), table_name='order_item_extras')
    op.drop_index(op.f('ix_order_item_extras_created_at'), table_name='order_item_extras')
    op.drop_table('order_item_extras')
    op.drop_index('ix_cart_item_extras_option_id', table_name='cart_item_extras')
    op.drop_index(op.f('ix_cart_item_extras_deleted_at'), table_name='cart_item_extras')
    op.drop_index(op.f('ix_cart_item_extras_created_at'), table_name='cart_item_extras')
    op.drop_index('ix_cart_item_extras_cart_item_id', table_name='cart_item_extras')
    op.drop_table('cart_item_extras')
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index(op.f('ix_order_items_deleted_at'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_coupon_usages_user_id', table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_order_id', table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_deleted_at'), table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_created_at', table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_coupon_id', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index('ix_cart_items_variant_id', table_name='cart_items')
    op.drop_index('ix_cart_items_product_id', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_deleted_at'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_created_at'), table_name='cart_items')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_wishlist_items_wishlist_id', table_name='wishlist_items')
    op.drop_index('ix_wishlist_items_product_id', table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_deleted_at'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_created_at'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_deleted_at'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_created_at'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_product_options_product_id', table_name='product_options')
    op.drop_index('ix_product_options_option_id', table_name='product_options')
    op.drop_index(op.f('ix_product_options_deleted_at'), table_name='product_options')
    op.drop_index(op.f('ix_product_options_created_at'), table_name='product_options')
    op.drop_table('product_options')
    op.drop_index('uq_product_images_product_order_active', table_name='product_images', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_product_images_primary', table_name='product_images', postgresql_where=sa.text('deleted_at IS NULL AND is_primary IS TRUE'))
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_index(op.f('ix_product_images_deleted_at'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_created_at'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('uq_orders_order_number_active', table_name='orders', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_payment_status', table_name='orders')
    op.drop_index(op.f('ix_orders_deleted_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_deal_products_product_id', table_name='deal_products')
    op.drop_index(op.f('ix_deal_products_deleted_at'), table_name='deal_products')
    op.drop_index('ix_deal_products_deal_id', table_name='deal_products')
    op.drop_index(op.f('ix_deal_products_created_at'), table_name='deal_products')
    op.drop_table('deal_products')
    op.drop_index('uq_wishlists_user_active', table_name='wishlists', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_wishlists_user_id', table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_deleted_at'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_created_at'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index('uq_products_slug_active', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('ix_products_is_visible', table_name='products')
    op.drop_index('ix_products_is_popular', table_name='products')
    op.drop_index('ix_products_is_featured', table_name='products')
    op.drop_index('ix_products_is_available', table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_notification_type', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_notification_preferences_user_active', table_name='notification_preferences', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_notification_preferences_deleted_at'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_created_at'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('uq_carts_user_active', table_name='carts', postgresql_where=sa.text('deleted_at IS NULL AND is_active IS TRUE'))
    op.drop_index('ix_carts_user_id', table_name='carts')
    op.drop_index(op.f('ix_carts_deleted_at'), table_name='carts')
    op.drop_index(op.f('ix_carts_created_at'), table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_addresses_default_per_user', table_name='addresses', postgresql_where=sa.text('deleted_at IS NULL AND is_default IS TRUE'))
    op.drop_index('ix_addresses_user_id', table_name='addresses')
    op.drop_index(op.f('ix_addresses_deleted_at'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_created_at'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('uq_variant_options_slug_active', table_name='variant_options', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_variant_options_option_type', table_name='variant_options')
    op.drop_index(op.f('ix_variant_options_deleted_at'), table_name='variant_options')
    op.drop_index(op.f('ix_variant_options_created_at'), table_name='variant_options')
    op.drop_table('variant_options')
    op.drop_index('uq_users_phone_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_system_settings_key_active', table_name='system_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_system_settings_is_public', table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_deleted_at'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_otp_logs_status', table_name='otp_logs')
    op.drop_index('ix_otp_logs_phone_number', table_name='otp_logs')
    op.drop_index('ix_otp_logs_expires_at', table_name='otp_logs')
    op.drop_index(op.f('ix_otp_logs_deleted_at'), table_name='otp_logs')
    op.drop_index('ix_otp_logs_created_at', table_name='otp_logs')
    op.drop_table('otp_logs')
    op.drop_index('uq_deals_slug_active', table_name='deals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_deals_starts_at', table_name='deals')
    op.drop_index('ix_deals_is_active', table_name='deals')
    op.drop_index('ix_deals_ends_at', table_name='deals')
    op.drop_index(op.f('ix_deals_deleted_at'), table_name='deals')
    op.drop_index('ix_deals_deal_type', table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_table('deals')
    op.drop_index('uq_coupons_code_active', table_name='coupons', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_coupons_is_active', table_name='coupons')
    op.drop_index('ix_coupons_expires_at', table_name='coupons')
    op.drop_index(op.f('ix_coupons_deleted_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_created_at'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('uq_categories_slug_active', table_name='categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_categories_is_visible', table_name='categories')
    op.drop_index('ix_categories_display_order', table_name='categories')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
